# Generated by Django 3.1.3 on 2020-11-07 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_code', message="Code must be in code format (AA000). Example: 'MV102'", regex='^[A-Za-z]{2}[0-9]{3}$')], verbose_name='Code')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.UniqueConstraint(condition=models.Q(status=True), fields=('code',), name='unique_vessel_code'),
        ),
    ]
