# Generated by Django 3.1.3 on 2020-11-07 19:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated DateTime')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Code must be alphanumeric', regex='^[A-Za-z0-9]*$')], verbose_name='Code')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vessel', verbose_name='Vessel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
